repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v20.1.0'
    hooks:
      - id: clang-format
        files: \.[ch]$
        # preserve upstream formatting
        exclude: ^(src/compat/compat-lz4\.[ch]|src/openvpn/ovpn_dco_(linux|win)\.h)$
